package freshness

import (
	"testing"
)

const sampleCargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "addr2line"
version = "0.24.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "gimli",
]

[[package]]
name = "tokio"
version = "1.50.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafebabe"
dependencies = [
 "bytes",
 "mio",
]

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"
`

func TestParseCargoLock_BasicVersions(t *testing.T) {
	t.Parallel()
	resolved := ParseCargoLock([]byte(sampleCargoLock))

	tests := []struct {
		name    string
		want    string
		present bool
	}{
		{"tokio", "1.50.0", true},
		{"serde", "1.0.219", true},
		{"addr2line", "0.24.2", true},
		{"nonexistent", "", false},
	}

	for _, tc := range tests {
		got, ok := resolved[tc.name]
		if ok != tc.present {
			t.Errorf("resolved[%q] present=%v, want %v", tc.name, ok, tc.present)
			continue
		}
		if tc.present && got != tc.want {
			t.Errorf("resolved[%q] = %q, want %q", tc.name, got, tc.want)
		}
	}
}

func TestParseCargoLock_Empty(t *testing.T) {
	t.Parallel()
	resolved := ParseCargoLock([]byte(""))
	if len(resolved) != 0 {
		t.Errorf("expected empty map, got %d entries", len(resolved))
	}
}

func TestParseCargoLock_NoTrailingNewline(t *testing.T) {
	t.Parallel()
	// Last block has no trailing blank line.
	input := `[[package]]
name = "hyper"
version = "1.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"`

	resolved := ParseCargoLock([]byte(input))
	if v, ok := resolved["hyper"]; !ok {
		t.Error("hyper not found in resolved map")
	} else if v != "1.5.0" {
		t.Errorf("hyper version = %q, want %q", v, "1.5.0")
	}
}

func TestParseCargoLock_HeaderOnly(t *testing.T) {
	t.Parallel()
	// File with header but no packages.
	input := `# This file is automatically @generated by Cargo.
version = 4
`
	resolved := ParseCargoLock([]byte(input))
	if len(resolved) != 0 {
		t.Errorf("expected empty map, got %d entries", len(resolved))
	}
}

func TestEnrichWithCargoLock_OverridesRangeVersions(t *testing.T) {
	t.Parallel()
	deps := []Dependency{
		{Name: "tokio", Version: "1", Language: langRust},
		{Name: "serde", Version: "1.0", Language: langRust},
		{Name: "local-crate", Version: "", Language: langRust},
	}
	resolved := map[string]string{
		"tokio": "1.50.0",
		"serde": "1.0.219",
	}

	EnrichWithCargoLock(deps, resolved)

	for _, dep := range deps {
		switch dep.Name {
		case "tokio":
			if dep.Version != "1.50.0" {
				t.Errorf("tokio version = %q, want %q", dep.Version, "1.50.0")
			}
		case "serde":
			if dep.Version != "1.0.219" {
				t.Errorf("serde version = %q, want %q", dep.Version, "1.0.219")
			}
		case "local-crate":
			if dep.Version != "" {
				t.Errorf("local-crate version = %q, want empty (not in lock)", dep.Version)
			}
		}
	}
}

func TestEnrichWithCargoLock_SkipsNonRust(t *testing.T) {
	t.Parallel()
	deps := []Dependency{
		{Name: "lodash", Version: "4.17.0", Language: "javascript"},
		{Name: "tokio", Version: "1", Language: langRust},
	}
	resolved := map[string]string{
		"lodash": "99.0.0", // should NOT override non-Rust dep
		"tokio":  "1.50.0",
	}

	EnrichWithCargoLock(deps, resolved)

	for _, dep := range deps {
		switch dep.Name {
		case "lodash":
			if dep.Version != "4.17.0" {
				t.Errorf("lodash version should be unchanged, got %q", dep.Version)
			}
		case "tokio":
			if dep.Version != "1.50.0" {
				t.Errorf("tokio version = %q, want %q", dep.Version, "1.50.0")
			}
		}
	}
}

func TestDiscoverManifests_CargoLockEnrichment(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	writeTestFile(t, dir, "Cargo.toml", `[package]
name = "myapp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1"
serde = { version = "1.0", features = ["derive"] }
`)

	writeTestFile(t, dir, "Cargo.lock", `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "myapp"
version = "0.1.0"

[[package]]
name = "tokio"
version = "1.50.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def"
`)

	manifests := DiscoverManifests(dir)
	if len(manifests) != 1 {
		t.Fatalf("manifests count = %d, want 1", len(manifests))
	}

	m := manifests[0]
	for _, dep := range m.Dependencies {
		switch dep.Name {
		case "tokio":
			if dep.Version != "1.50.0" {
				t.Errorf("tokio version = %q, want 1.50.0 (from Cargo.lock)", dep.Version)
			}
		case "serde":
			if dep.Version != "1.0.219" {
				t.Errorf("serde version = %q, want 1.0.219 (from Cargo.lock)", dep.Version)
			}
		}
	}
}

func TestDiscoverManifests_CargoNoLock(t *testing.T) {
	t.Parallel()
	// Without Cargo.lock, versions from Cargo.toml should be preserved as-is.
	dir := t.TempDir()

	writeTestFile(t, dir, "Cargo.toml", `[package]
name = "mylib"
version = "0.1.0"

[dependencies]
serde = "1.0"
`)

	manifests := DiscoverManifests(dir)
	if len(manifests) != 1 {
		t.Fatalf("manifests count = %d, want 1", len(manifests))
	}

	m := manifests[0]
	if len(m.Dependencies) != 1 {
		t.Fatalf("dep count = %d, want 1", len(m.Dependencies))
	}
	if m.Dependencies[0].Version != "1.0" {
		t.Errorf("serde version = %q, want 1.0 (original)", m.Dependencies[0].Version)
	}
}
